server:
  port: 8080
mybatis:
  # mapper文件哪里找
  mapper-locations: classpath*:/mybatis/**/*.xml
  # 类型别名指定的基本的包
  type-aliases-package: com.lucky.model
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 微信公众号模式
wechat:
  mpAppId: wx91dc53ac833139e7
  mpAppSecret: 6b2def641e1bd1d799bdc8fe7c96c174
  # 不是微信刻意规定的，用户点了同意之后，调用的接口地址
  # userInfoUrl: http://1ao5msve.shenzhuo.vip:50999/admin/wechat/userInfo

  userInfoUrl: http://8.140.60.3:8080/admin/wechat/userInfo
  # '#' 传输有问题，所以用一个字符串来代替#
  replaceStr: xxxxxx

deploy:
  front: http://8.140.60.3:9090
  rear: http://8.140.60.3:8080

# 整合分页插件
pagehelper:
  autoRuntimeDialect: true
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckyoadb?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Chenyingxiang18.
  mvc:
    # 内容协商，自定义浏览器接收类型，通过参数format
    # contentnegotiation:
    # favor-parameter: true
    # 开启请求体的，方法类型解析
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 整合Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  activiti:
    # database-schema-update可以取值 ：
    #    false:默认，数据库表不变，但是如果版本不对或者缺失表会抛出异常（生产使用）
    #    true:表不存在，自动创建（开发使用）
    #    create_drop: 启动时创建，关闭时删除表（测试使用）
    #    drop_create: 启动时删除表,在创建表 （不需要手动关闭引擎）
    database-schema-update: true

    # 监测历史表是否存在，activities7默认不开启历史表
    # 历史表的主要作用是帮助用户回溯和查看Activity的执行过程，以及在需要时进行数据恢复。
    db-history-used: true

    #none：不保存任何历史数据，流程中这是最高效的
    #activity：只保存流程实例和流程行为
    #audit：除了activity，还保存全部的流程任务以及其属性，audit为history默认值
    #full：除了audit、还保存其他全部流程相关的细节数据，包括一些流程参数
    history-level: full

    #校验流程文件，默认校验resources下的process 文件夹的流程文件
    check-process-definitions: true
