server:
  port: 8080
mybatis:
  # mapper文件哪里找
  mapper-locations: classpath*:/mybatis/**/*.xml
  # 类型别名指定的基本的包
  type-aliases-package: com.lucky.model.system
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 整合分页插件
pagehelper:
  autoRuntimeDialect: true
  reasonable: true #为了使用输入页数为负或者超出最大页时候使页数为最小或最大值
  supportMethodsArguments: true # 支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: count=countSql # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.118:3307/oadb?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: chen18
  mvc:
    # 内容协商，自定义浏览器接收类型，通过参数format
#    contentnegotiation:
#      favor-parameter: true

    # 开启请求体的，方法类型解析
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8